CREATE TABLE skills (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  category text not null,
  percentage integer check (percentage >= 0 and percentage <= 100),
  proficiency_level text, -- 'Expert', 'Advanced', 'Intermediate', 'Beginner'
  icon_name text -- React Icons name or Lucide icon name
);

-- Insert some sample data (optional, but good for testing)
INSERT INTO skills (name, category, percentage, proficiency_level, icon_name) VALUES
('React', 'FRAMEWORKS', 90, 'Expert', 'FaReact'),
('Tailwind CSS', 'FRAMEWORKS', 95, 'Expert', 'SiTailwindcss'),
('Node.js', 'FRAMEWORKS', 85, 'Expert', 'FaNodeJs'),
('TypeScript', 'LANGUAGES', 80, 'Advanced', 'SiTypescript'),
('Python', 'LANGUAGES', 75, 'Advanced', 'FaPython'),
('PostgreSQL', 'DATABASES', 70, 'Advanced', 'BiLogoPostgresql'),
('Flutter', 'FRAMEWORKS', 65, 'Intermediate', 'SiFlutter'),
('Docker', 'TOOLS', 60, 'Intermediate', 'FaDocker');
