CREATE TABLE projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  image_url text,
  tags text[],
  category text,
  demo_link text,
  repo_link text
);

CREATE TABLE education (
  id bigint generated by default as identity primary key,
  degree text,
  institution text,
  period text,
  score text,
  details text
);

CREATE TABLE experience (
  id bigint generated by default as identity primary key,
  role text,
  company text,
  period text,
  description text,
  type text
);

CREATE TABLE messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  message text
);
